### PR TITLE
data_cleaning first commit

### LINKED ISSUE #2: Handling missing data
This is the first phase and one of the most important phases. We will need to clean the data and the deadline iline is Sunday, 4th October, 2018

### LINKED ISSUE #4: Dropping irrelevant columns
This is also part of cleaning the data. We are to drop irrelevant columns based on your judgement. Don't worry we will also review when pull request are made

### PR DESCRIPTION
**Pull request by Osei365**
I posted the data dictionary as a CSV file
I also did some data cleaning, dropped some columns
I posted the notebook that contains the code used

### CODE REVIEW

**Comment by jideilori** [comment]
split_join() function i.e line 90 gives "ValueError: split() requires a non-empty pattern match."

**Comment by Osei365** [comment]
Sorry, did you run the code on your PC?.
Cause `re` has to be imported. I mistakenly deleted the code I used to import.
It worked cause the import was already in the memory.
That code was to convert the currency from object to float

**Comment by jideilori** [comment]
I used colab and I wish to understand why you dropped some columns. Lastly, when saving to csv use "final_data.to_csv('new_project_data.csv',index=False)" to avoid it adding another index column.

**Comment by Osei365** [comment]
Okay, noted sir
The columns had a lot of missing data, most of which had like 7 to 200 Not null samples out of 1815.
I used a criterion to select the columns that were not dropped sir

The columns were so intercorrelated that they had a correlation of 1 with columns other than themselves. Which implies a high level of multicollinearity.
So I selected columns that have high correlations with at least 10 other columns and with at most 200 missing values.
I used missing values as a criterion cause some correlations can't be trusted, the large number of Nan values were correlated as well.

**Pull request merged**
