### PR TITLE
testing version

### PR DESCRIPTION
**Pull request by Osei365**
This is the data for the project, it is subject to a lot of cleaning and preprocessing. I'm doing this to test the pull request

### CODE REVIEW

**Comment by Osei365** [comment]
Hi, at everyone, I added the data from kaggle to the data folder. About 1817 rows and 51 columns

**Comment by HydroPsalm** [comment]
Alright, nice one bro!

**Comment by Osei365** [comment]
I want everyone to see it before I  merge it with the base repo

**Comment by OLAMILEKANSI5** [comment]
Awesome bro. You can ahead

**Pull request merged**
